Legg til jobb for å ta backup av Sanity-datasett
biblioteksentralen/github-actions pull request #2
Opened 2022-01-12 13:54 UTC by jfulse

2022-01-12 14:55 UTC, danmichaelo requested changes
Kult, veldig elegant løsning 👏 

Lurte litt på om fila skulle hatt litt mer informasjon i filnavnet, f.eks.

    BACKUP_FILENAME=backup-${{ inputs.dataset-name }}-$(date +%Y-%m-%d).tar.gz

Kan være litt praktisk for å ikke gå i surr med filer en laster ned, hvis vi må sjekke flere backuper.

2022-01-12 14:55 UTC, danmichaelo commented on sanity-dataset-backup/action.yml
> +      run: npx sanity dataset export production backups/backup.tar.gz
```suggestion
      run: npx sanity dataset export ${{ inputs.dataset-name }} backups/backup.tar.gz
```

2022-01-12 15:19 UTC, jfulse commented
> Lurte litt på om fila skulle hatt litt mer informasjon i filnavnet, f.eks.

God ide, jeg endrer 👍

2022-01-12 15:20 UTC, jfulse commented on sanity-dataset-backup/action.yml
> +      run: npx sanity dataset export production backups/backup.tar.gz
Ops glemte det ja, hehe

2022-01-12 16:57 UTC, danmichaelo requested changes

2022-01-12 16:57 UTC, danmichaelo commented on sanity-dataset-backup/action.yml
> +    - name: Upload backup.tar.gz and store for ${{ env.RETENTION_DAYS }} days
```suggestion
    - name: Upload ${{ env.BACKUP_FILE_NAME }} and store for ${{ env.RETENTION_DAYS }} days
```

2022-01-12 16:57 UTC, danmichaelo commented on sanity-dataset-backup/action.yml
> +        name: backup-tarball
```suggestion
        name: ${{ env.BACKUP_FILE_NAME }}
```

(når jeg tenker meg om er det vel egentlig *bare* her vi trenger å ha et meningsbærende navn, men jaja :D)

2022-01-13 09:06 UTC, jfulse commented on sanity-dataset-backup/action.yml
> +        name: backup-tarball
Godt poeng. Men det skader ikke 🙂

2022-01-13 10:44 UTC, danmichaelo approved these changes
👏

2022-01-14 11:33 UTC, merged